// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiS-cvPe-s0WkLmiHko7J7UEhjIx9WM8M',
    appId: '1:448602665004:web:089a5ba88182376ccae189',
    messagingSenderId: '448602665004',
    projectId: 'pcify-platform',
    authDomain: 'pcify-platform.firebaseapp.com',
    storageBucket: 'pcify-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuEGftWpJNQZlBacKIW82Za7RvfbBzt8',
    appId: '1:448602665004:android:68adc24b8369f17bcae189',
    messagingSenderId: '448602665004',
    projectId: 'pcify-platform',
    storageBucket: 'pcify-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQxEHRFfEfVZDzapdNuNU7ymW9RDrLJSU',
    appId: '1:448602665004:ios:3ef3f1a6153bf59ecae189',
    messagingSenderId: '448602665004',
    projectId: 'pcify-platform',
    storageBucket: 'pcify-platform.firebasestorage.app',
    iosBundleId: 'com.example.pcify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQxEHRFfEfVZDzapdNuNU7ymW9RDrLJSU',
    appId: '1:448602665004:ios:3ef3f1a6153bf59ecae189',
    messagingSenderId: '448602665004',
    projectId: 'pcify-platform',
    storageBucket: 'pcify-platform.firebasestorage.app',
    iosBundleId: 'com.example.pcify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiS-cvPe-s0WkLmiHko7J7UEhjIx9WM8M',
    appId: '1:448602665004:web:9c462d6131ccdb6ccae189',
    messagingSenderId: '448602665004',
    projectId: 'pcify-platform',
    authDomain: 'pcify-platform.firebaseapp.com',
    storageBucket: 'pcify-platform.firebasestorage.app',
  );
}
